app:
  url: "https://robot-dreams-de-api.herokuapp.com"
  auth_endpoint: "/auth"
  endpoint: "/out_of_stock"
  directory: "/home/user/data/"
  db_connection_id: "dz5_pg_connection"
  hdfs_connection_id: "dz5_hdfs_connection"
  username: ""
  password: ""

logger:
  level: "DEBUG"
